trying to fix issue with node images version

diff --git a/.github/workflows/Pipeline.yml b/.github/workflows/Pipeline.yml
--- a/.github/workflows/Pipeline.yml
+++ b/.github/workflows/Pipeline.yml
@@ -66,8 +66,10 @@ jobs:
             for version in "${versions[@]}"; do
               if [ -n "$version" ]; then
                 echo "key is: $key , version is: $version"
+                # trap 'echo "Error occurred for $key:$item"; continue' ERR
+                trivy image -f json -o "trivy-reports/${key}_${version}.json" "$key:$version" 2>/dev/null
                 trap 'echo "Error occurred for $key:$item"; continue' ERR
-                trivy image -f json -o "trivy-reports/${key}_${version}.json" "$key:$version" 2>/dev/null              
+              
               fi 
               # You can perform your desired actions here for each item
             done
